config/routes.rb
Rshortener::Application.routes.draw do
  resources :links
  resources :visitors
  match ':id' => "links#show", via: :get
  root to: "links#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
	has_many  :visitors
	validates :original_url, :format => URI::regexp(%w(http https))
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		redirect_to action:'new'
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(post_params)

		#generate url and test 
		@link.shortened_url = generate_random_string

		if @link.save
			flash[:notice] = "Link created. " + request.protocol + request.host + "/" + @link.shortened_url
			redirect_to action:'new'
		else
			render 'new'
		end
	end

	def show
		link = Link.find_by_shortened_url(params[:id])

		#create an entry for the visited link
		link.visitors.create(:ipaddr => request.remote_ip)

		respond_to do |format|
		  format.html {
		  	redirect_to link.original_url
		  }
	      format.xml  { render xml: link }
	      format.json { render json: link }
	    end

	end

	private 

		def generate_random_string(size = 5)
			charset = ('a'..'z').to_a + (0..9).to_a
			(0...size).map{ charset.to_a[rand(charset.size)] }.join
		end

		def post_params
			params.require(:link).permit(:original_url)
		end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		@links = Link.joins(:visitors).select("links.*, count(visitors.link_id) as visitors_count").order("visitors_count DESC").group("links.id")
	end

	def show
		link = Link.find_by_shortened_url(params[:id])
		if link.nil?
			link = Link.find(params[:id])
		end
		@visitors = link.visitors
		respond_to do |format|
		  format.html 
	      format.xml  { render xml: @visitors }
	      format.json { render json: @visitors }
	    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.1.1"
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rshortener</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<div class="site-wrapper">

	  <div class="site-wrapper-inner">

	    <div class="cover-container">

	      <div class="masthead clearfix">
	        <div class="inner" style="margin-top: 20px;">
	          <h3 class="masthead-brand"><a href="/" class="logo">rShortener</a></h3>
	          <ul class="nav masthead-nav">
                <li class="active"><%= link_to 'Visitor Information', controller: :visitors %></li>
              </ul>
	        </div>
	      </div>

	      <div class="inner cover">
	      	<%= yield %>

	      	
			<% flash.each do |name, msg| -%>
				  <%= content_tag :div, msg, class: "alert alert-success" %>
			<% end -%>
	      </div>


	    </div>

	  </div>

	</div>


<script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>


</body>
</html>

app/views/links/new.html.erb
<h1 class="cover-heading">Shorten your URLs.</h1>

<p class="lead">

	<%= form_for :link, url: links_path, :html => { :class => "form-inline", :role => "form"} do |f| %>

		<% if @link.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@link.errors.count, "error") %>.</h2>
			<ul>
			<% @link.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
		<% end %>

		<div class="form-group">
			<%= f.text_field :original_url, :placeholder => "Enter a url to shorten it", class: "form-control input-mysize" %>
		</div>

		<div class="form-actions" style="margin-top: 20px;">
			<%= f.submit "Shortify!", class: "btn btn-lg btn-info" %>
		</div>

	<% end %>	
</p>

app/views/visitors/index.html.erb
<div class="table-responsive">
<table class="table">
	<thead>
		<tr>
			<th>Url</th>
			<th>Visits</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @links.each do |link| %>
		<tr>
	  		<td><%= link.original_url %></td>
	  		<td><%= link.visitors_count %></td>
	  		<td class="underline"><%= link_to link.shortened_url, :controller => :visitors, :action => :show, :id => link.id %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/visitors/show.html.erb
<div class="table-responsive">
<table class="table">
	<thead>
		<tr>
			<th>Visitor IP</th>
			<th>Date</th>
		</tr>
	</thead>
	<tbody>
		<% @visitors.each do |visitor| %>
		<tr>
	  		<td><%= visitor.ipaddr %></td>
	  		<td><%= visitor.created_at %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>